# ============================
# DEV PROFILE ? IDE + DB en Docker (localhost:5467)
# ============================

# --- Datasource ---
spring.datasource.url=${POSTGRES_DEV_URL:jdbc:postgresql://localhost:5467/traveldesk_db}
spring.datasource.username=${POSTGRES_DEV_USER:postgres}
spring.datasource.password=${POSTGRES_DEV_PASSWORD:postgres}
spring.jpa.database=POSTGRESQL
spring.sql.init.platform=postgres

# --- DDL: Flyway gestiona el esquema; Hibernate solo valida ---
spring.jpa.hibernate.ddl-auto=validate

# --- Frontend local ---
app.reset-password.base-url=${RESET_PASSWORD_BASE_URL:http://localhost:4200/reset-password}
app.accept-invite.base-url=${ACCEPT_INVITE_BASE_URL:http://localhost:4200/accept-invite}

# --- Logging detallado en dev ---
spring.jpa.show-sql=true
logging.level.com.crishof=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
